import type { Metadata } from "next";
import { Montserrat, Playfair_Display } from "next/font/google";
import "../styles/global.css";

const fontSans = Montserrat({
	subsets: ["latin"],
	display: "block",
	variable: "--font-sans",
});

const fontSerif = Playfair_Display({
	subsets: ["latin"],
	display: "block",
	variable: "--font-serif",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className={`${fontSans.variable} ${fontSerif.variable}`}>
			<body>{children}</body>
		</html>
	);
}
