import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import "../styles/global.css";

const fontSans = Inter({ subsets: ["latin"], variable: "--font-sans" });

const fontDisplay = Playfair_Display({
	weight: ["400", "600", "800"],
	subsets: ["latin"],
	display: "swap",
	variable: "--font-display",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={fontSans.className}>{children}</body>
		</html>
	);
}
